package com.koemdzhiev.georgi.funfacts;

import java.util.Random;

/**
 * Created by Georgi on 5/8/2015.
 */
public class FactBook {

    //member variables
    public String[] mFacts = {
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "Our oldest radio broadcasts of the 1930s have already traveled past 100,000 stars",
            "It takes 8 minutes 17 seconds for light to travel from the Sun's surface to the Earth.",
            "October 12th, 1999 was declared 'The Day of Six Billion' based on United Nations projections.",
            "10 percent of all human beings ever born are alive at this very moment.",
            "The Earth spins at 1,000 mph but it travels through space at an incredible 67,000 mph.",
            "Every year over one million earthquakes shake the Earth.",
            "When Krakatoa erupted in 1883, its force was so great it could be heard 4,800 kilometers away in Australia.",
            "The largest ever hailstone weighed over 1kg and fell in Bangladesh in 1986.",
            "Every second around 100 lightning bolts strike the Earth.",
            "Every year lightning kills 1000 people.",
            "In October 1999 an Iceberg the size of London broke free from the Antarctic ice shelf.",
            "If you could drive your car straight up you would arrive in space in just over an hour.",
            "Human tapeworms can grow up to 22.9m.",
            "The Earth is 4.56 billion years old, the same age as the Moon and the Sun.",
            "The dinosaurs became extinct before the Rockies or the Alps were formed.",
            "Female black widow spiders eat their males after mating.",
            "When a flea jumps, the rate of acceleration is 20 times that of the space shuttle during launch.",
            "If our Sun were just inch in diameter, the nearest star would be 445 miles away.",
            "The Australian billygoat plum contains 100 times more vitamin C than an orange.",
            "Astronauts cannot belch - there is no gravity to separate liquid from gas in their stomachs.",
            "The air at the summit of Mount Everest, 29,029 feet is only a third as thick as the air at sea level.",
            "One million, million, million, million, millionth of a second after the Big Bang the Universe was the size of a ...pea.",
            "DNA was first discovered in 1869 by Swiss Friedrich Mieschler.",
            "The molecular structure of DNA was first determined by Watson and Crick in 1953.",
            "The first synthetic human chromosome was constructed by US scientists in 1997.",
            "The thermometer was invented in 1607 by Galileo.",
            "Englishman Roger Bacon invented the magnifying glass in 1250.",
            "Alfred Nobel invented dynamite in 1866.",
            "Wilhelm Rontgen won the first Nobel Prize for physics for discovering X-rays in 1895.",
            "The tallest tree ever was an Australian eucalyptus - In 1872 it was measured at 435 feet tall.",
            "Christian Barnard performed the first heart transplant in 1967 - the patient lived for 18 days.",
            "The wingspan of a Boeing 747 is longer than the Wright brother's first flight.",
            "An electric eel can produce a shock of up to 650 volts.",
            "'Wireless' communications took a giant leap forward in 1962 with the launch of Telstar, the first satellite capable of relaying telephone and satellite TV signals.",
            "The earliest wine makers lived in Egypt around 2300 BC.",
            "The Ebola virus kills 4 out of every 5 humans it infects.",
            "In 5 billion years the Sun will run out of fuel and turn into a Red Giant.",
            "Giraffes often sleep for only 20 minutes in any 24 hours. They may sleep up to 2 hours (in spurts - not all at once), but this is rare. They never lie down.",
            "A pig's orgasm lasts for 30 minutes.",
            "Without its lining of mucus your stomach would digest itself.",
            "Humans have 46 chromosomes, peas have 14 and crayfish have 200.",
            "There are 60,000 miles of blood vessels in the human body.",
            "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
            "Utopia ia a large, smooth lying area of Mars.",
            "On the day that Alexander Graham Bell was buried the entire US telephone system was shut down for 1 minute in tribute.",
            "The low frequency call of the humpback whale is the loudest noise made by a living creature.",
            "The call of the humpback whale is louder than Concorde and can be heard from 500 miles away.",
            "A quarter of the world's plants are threatened with extinction by the year 2010.",
            "Each person sheds 40lbs of skin in his or her lifetime.",
            "At 15 inches the eyes of giant squids are the largest on the planet.",
            "The largest galaxies contain a million, million stars.",
            "The Universe contains over 100 billion galaxies.",
            "Wounds infested with maggots heal quickly and without spread of gangrene or other infection.",
            "More germs are transferred shaking hands than kissing.",
            "The longest glacier in Antarctica, the Almbert glacier, is 250 miles long and 40 miles wide.",
            "The fastest speed a falling raindrop can hit you is 18mph.",
            "A healthy person has 6,000 million, million, million hemoglobin molecules.",
            "A salmon-rich, low cholesterol diet means that Inuits rarely suffer from heart disease.",
            "Inbreeding causes 3 out of every 10 Dalmatian dogs to suffer from hearing disability.",
            "The world's smallest winged insect, the Tanzanian parasitic wasp, is smaller than the eye of a housefly.",
            "If the Sun were the size of a beach ball then Jupiter would be the size of a golf ball and the Earth would be as small as a pea.",
            "It would take over an hour for a heavy object to sink 6.7 miles down to the deepest part of the ocean.",
            "There are more living organisms on the skin of each human than there are humans on the surface of the earth.",
            "The grey whale migrates 12,500 miles from the Arctic to Mexico and back every year.",
            "Each rubber molecule is made of 65,000 individual atoms.",
            "Around a million, billion neutrinos from the Sun will pass through your body while you read this sentence.",
            "Quasars emit more energy than 100 giant galaxies.",
            "Quasars are the most distant objects in the Universe.",
            "The Saturn V rocket which carried man to the Moon develops power equivalent to fifty 747 jumbo jets.",
            "Koalas sleep an average of 22 hours a day, two hours more than the sloth.",
            "Light would take .13 seconds to travel around the Earth.",
            "Males produce one thousand sperm cells each second - 86 million each day.",
            "Neutron stars are so dense that a teaspoonful would weigh more than all the people on Earth.",
            "One in every 2000 babies is born with a tooth.",
            "Every hour the Universe expands by a billion miles in all directions.",
            "Somewhere in the flicker of a badly tuned TV set is the background radiation from the Big Bang.",
            "Even traveling at the speed of light it would take 2 million years to reach the nearest large galaxy, Andromeda.",
            "The temperature in Antarctica plummets as low as -35 degrees Celsius.",
            "At over 2000 kilometers long The Great Barrier Reef is the largest living structure on Earth.",
            "A thimbleful of a neutron star would weigh over 100 million tons.",
            "The risk of being struck by a falling meteorite for a human is one occurrence every 9,300 years.",
            "The driest inhabited place in the world is Aswan, Egypt where the annual average rainfall is .02 inches.",
            "The deepest part of any ocean in the world is the Mariana trench in the Pacific with a depth of 35,797 feet.",
            "The largest meteorite craters in the world are in Sudbury, Ontario, Canada and in Vredefort, South Africa.",
            "The largest desert in the world, the Sahara, is 3,500,000 square miles.",
            "The largest dinosaur ever discovered was Seismosaurus who was over 100 feet long and weighed up to 80 tonnes.",
            "The African Elephant gestates for 22 months.",
            "The short-nosed Bandicoot has a gestation period of only 12 days.",
            "The mortality rate if bitten by a Black Mamba snake is over 95%.",
            "In the 14th century the Black Death killed 75,000,000 people. It was carried by fleas on the black rat.",
            "A dog's sense of smell is 1,000 times more sensitive than a humans.",
            "A typical hurricane produces the nergy equivalent to 8,000 one megaton bombs.",
            "90% of those who die from hurricanes die from drowning.",
            "To escape the Earth's gravity a rocket need to travel at 7 miles a second.",
            "If every star in the Milky Way was a grain of salt they would fill an Olympic sized swimming pool.",
            "Microbial life can survive on the cooling rods of a nuclear reactor.",
            "Micro-organisms have been brought back to life after being frozen in perma-frost for three million years.",
            "The speed of light is generally rounded down to 186,000 miles per second. In exact terms it is 299,792,458 m.s (meters per second - that is equal to 186, 287.49 miles per second).",
            "You breathe on average about 5 million times a year.",
            "Months that begin on a Sunday always have a Friday the 13th in them.",
            "You are born with 300 bones, by the time you are an adult you will have 206.",
            "The average lead pencil will write a line about 35 miles long or write approximately 50,000 English words.",
            "One fourth of the bones in your body are in your feet.",
            "The average person spends 2 weeks of their lifetime waiting for the light to change from red to green.",
            "It takes more calories to eat a piece of celery than the celery has in it.",
            "The present population is expected to rise to 15 Billion by the year 2080.",
            "The largest recorded snowflake was 15 inches wide and 8 inches thick.",
            "The tip of a bullwhip moves so fast that the sound it makes is actually a tiny sonic boom.",
            "Native Americans used to name their children after the first thing they saw as they left their tepees after their children were born, hence the names Sitting Bull and Running Water.",
            "The Matami Tribe of West Africa play their own version of football, instead of a normal football they use a human skull.",
            "Coca-Cola would be green if the food colorant wasn't added.",
            "During the 17th Century, the Sultan of Turkey ordered his hole harem of women to be drowned and replaced with a new one.",
            "Coffins used for cremation are usually made with plastic handles.",
            "\"Almost\" is the longest word in the English language with all the letters in alphabetical order.",
            "Human thigh bones are stronger than concrete.",
            "Cockroaches can live several weeks with their heads cut off.",
            "It is impossible to sneeze with your eyes open. We dare you, give it a try!",
            "A Ten Gallon Hat will only hold 3/4 of a Gallon.",
            "Of all the words in the English language, the word ìSETî has the most definitions.",
            "It is against the law to burp, or sneeze inside a church in Nebraska.",
            "In 1386 a pig in France was executed by public hanging for the murder of a child.",
            "Earth is the only planet not named after a god.",
            "The world's oldest piece of chewing gum is over 9,000 years old!",
            "Scientists have tracked butterflies travelling over 3,000 miles.",
            "The silkworm consumes 86,000 times its own weight in 56 days.",
            "If removed from the stress of the modern world, the average human would sleep about 10 hours a day.",
            "To produce a single pound of honey, a single bee would have to visit 2 million flowers.",
            "A colony of 500 bats can eat approximately 250,000 insects in an hour.",
            "One in Five adults believe that aliens are hiding in our planet disguised as humans.",
            "Travelling masseuses in ancient Japan were required by law to be blind.",
            "The bloodhound is the only animal whose evidence is admissible in court.",
            "James Fixx, the man who popularized jogging in America died of a heart attack while running.",
            "The average American spends about a year and a half of his or her life watching commercials on television. What are you doing?! Get out and spend that year and a half doing something productive!",
            "Ancient Greeks practiced a form (ineffective) of birth control that consisted of having a woman hold her breath, making her squat, and sneezing.",
            "The FDA permits up to 5 whole insects per 100 grams of apple butter.",
            "There are no naturally occurring blue foods, even blueberries are purple!",
            "The skeleton of Jeremy Bentham is present in all the important meetings of the University of London.",
            "The elephant is the only mammal that can't jump!",
            "Just like fingerprints, everyone's tongue is different.",
            "The longest recorded flight of a chicken is 13 seconds.",
            "400 Quarter Pounders can be made from a single cow.",
            "Only 38% of Americans eat breakfast every day.",
            "11% of the World is left handed.",
            "A \"Jiffy\" is the scientific name for 1/100th  of a second.",
            "A Boeing 747's wingspan is longer than the Wright brothers first flight.",
            "A broken clock is right two times a day.",
            "A duck's quack doesn't echo anywhere, no one knows why.",
            "Turtles can breathe through their butts.",
            "The Beatles used the word “love” 613 times in their songs.",
            "Blind people smile even though they’ve never seen anyone else smile.",
            "The elements that we are composed of were formed in the interiors of collapsing stars. We are all made of star dust.",
            "When you were born, you were, for a moment, the youngest person on earth.",
            " Sea otters hold hands when they sleep to keep from drifting apart.",
            " Squirrels plant thousands of new trees each year simply by forgetting where they put their acorns.",
            "Macaques in Japan use coins to buy vending machine snacks.",
            "In China, killing a Panda is punishable by death.",
            "The voices of Mickey Mouse and Minnie Mouse got married in real life.",
            "Gentoo penguins propose to their lifemates with a pebble.",
            "Kissing burns 2 calories a minute. Undressing burns 8.",
            "Google, the periodic table, the structure of our DNA, and “Yesterday” by the Beatles are all ideas that were conceived in dreams.",
            "In a 2008 survey, 58% of British teens thought Sherlock Holmes was a real guy, while 20% thought Winston Churchill was not.",
            "Nutella was invented during WWII, when an Italian pastry maker mixed hazelnuts into chocolate to extend his chocolate ration.",
            "A British man changed his name to Tim Pppppppppprice to make it harder for telemarketers to pronounce.",
            "J.P. Morgan once offered $100,000 to anyone who could figure out why his face was so red. No one solved the mystery.",
            "Prairie dogs say hello with kisses.",
            "Jonas Salk declined to patent his polio vaccine. \"There is no patent,\" he said. \"Could you patent the sun?\"",
            "After Leonardo da Vinci's death, King Francis I of France hung the Mona Lisa in his bathroom.",
            "Human fingers are so sensitive, that if your fingers were the size of Earth, you could feel the difference between a house and a car.",
            "With the 60,000 miles of blood vessels inside the average human body, you could circumnavigate Earth two and a half times.",
            "The human eye is so sensitive that if the Earth were flat, you could spot a candle flickering at night from up to 30 miles away.",
            "Nerve impulses travel to and from the brain at speeds of up to 250 miles per hour, faster than a Formula 1 racecar.",
            "When you blush, the lining of your stomach blushes too.",
            "The human brain can read up to 1,000 words per minute.",
            "Inside your belly button are thousands of bacteria that form an ecosystem the size of an entire rainforest.",
            "You can see ultraviolet light, the ability is just filtered out by the eye’s lens. Some people have undergone surgery to remove the lense and can detect ultraviolet light.",
            "Our muscles are actually incredibly more powerful than they appear to be. Human strength is limited to protect our tendons and muscles from harming themselves. This limitation can be removed during an adrenaline rush, during which some people have lifted boulders or even cars off themselves.",
            "We humans are the best long-distance runners on the planet. Better than any four-legged animal. In fact, thousands of years ago we used to run after our prey until they died of exhaustion.",
            "A full head of human hair is strong enough to support 12 tonnes.",
            "In 30 minutes, the human body gives off enough heat to bring a gallon of water to the boil",
            "The focusing muscles in your eyes move around 100,000 times a day. To give your leg muscles the same workout, you’d need to walk 50 miles.",
            "For every pound of fat or muscle gained, your body creates seven miles of new blood vessels",
            "Humans share 50% of their DNA with bananas.",
            "Humans shed 40 pounds of skin in their lifetime, completely replacing their outer skin every month.",
            "Around 90% of the cells that make humans aren’t “human” in origin. We’re mostly fungi and bacteria.",
            "The human brain uses 20% of the entire body’s oxygen and calorie intake, despite only accounting for about 2% of an adult’s body mass.",
            "We also produce differently structured tears depending on the reason we’re crying. When put under the microscope, crying over grief, hope, or onions all produced a unique tear.",
            "You’re a little richer than you might think. Inside all of us is around 0.2 milligrams of gold, most of which is in our blood Sadly, you’d need the blood of around 40,000 people to collect enough gold to make one 8g coin.",
            "Your body produces 25 million new cells each second. Every 13 seconds, you produce more cells than there are people in the United States."
    };
    //Methods
    public String getFact(){
        String fact = "";
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mFacts.length);
        fact = mFacts[randomNumber];
        return fact;
    }

        public String[] getFacts() {
                return mFacts;
        }

        public void setFacts(String[] facts) {
                mFacts = facts;
        }
}
